version: 2.1

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  test-linux:
    docker:
      - image: sudachen/go1137-ci

    parallelism: 1

    environment:
      MXNET_ENFORCE_DETERMINISM: 1
      OMP_NUM_THREADS: 4
      MXNET_OMP_MAX_THREADS: 4
      CC_TEST_REPORTER_ID: 1fa4e7523c328c9429acef9148195f67755088bba7c2378e6bac9c21c420dd1b


    steps:
      - checkout
      - run: make build
      - run: make run-tests
      #- run: /usr/local/bin/cc-test-reporter after-build -t gocov

      - run: make win-build-all
      - run: mkdir bin
      - run: cp tests.exe bin
      - persist_to_workspace:
          root: .
          paths:
            - bin

  test-windows:
    executor: win/default
    #shell: cmd.exe

    steps:
      - attach_workspace:
          at: .\ws
      - run: dir /s
      - run: .\ws\bin\tests.exe -test.v=true -test.coverprofile=c.out

workflows:
  version: 2
  test-workflow:
    jobs:
      - test-linux
      - test-windows:
          requires:
            - test-linux



